[package]
name = "x-lang"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
rpds = "0.5"
