[package]
name = "x-lang"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
edition = "2018"

[profile.release]
debug = 1

[dependencies]
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
rpds = "0.5"
bincode = "1"
